### ISSUE TITLE
Incompatible with ubuntu 14.04 (LTS)?

### ISSUE THREAD

**Issue by thorsummoner** [portal-chan/Isaac-Character-Editor#1]
OS: Mint 17.2 rafaela
Kernel: x86_64 Linux 3.16.0-38-generic
gcc: gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

```
isaaccharactereditor $./IsaacCharacterEditor.sh
isaaccharactereditor/Linux/./IsaacCharacterEditor: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by isaaccharactereditor/Linux/./IsaacCharacterEditor)
isaaccharactereditor/Linux/./IsaacCharacterEditor: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by isaaccharactereditor/Linux/./IsaacCharacterEditor)
isaaccharactereditor/Linux/./IsaacCharacterEditor: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by isaaccharactereditor/Linux/./IsaacCharacterEditor)
```

I tried modifying the shell script to include in the LD_LIBRARY_PATH:

 - `/usr/lib/x86_64-linux-gnu/` as suggested in http://askubuntu.com/questions/622926/ didn't work
 - `/usr/local/lib64/` as suggested in http://stackoverflow.com/questions/20357033/ didn't work

At this point I'm suspecting this program was compiled with a newer version of gcc than what Ubuntu LTS currently supports. http://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-4-9-on-ubuntu-14-04

Ideas?

**Comment by portal-chan** [comment]
I included the `libstdc++.so.6` that I had in my Ubuntu 15.10 installation and tried it on a fresh Mint 17.2 install, now it works.

**Comment by thorsummoner** [comment]
Oh awesome, I should replace my copy with a fresh download from themoddingofissac site? Eg is the binary release there updated?

**Comment by portal-chan** [comment]
Updated both here and there.
