### ISSUE TITLE
Is this ironic?

### ISSUE THREAD

**Issue by mcfuckingkillyourself** [portal-chan/Isaac-Character-Editor#2]
:^)

**Comment by portal-chan** [comment]
Oh come on, you could've at the very least used your actual account, coward.

**Comment by mcfuckingkillyourself** [comment]
You still didn't answer my question.
At least put a disclaimer, this is too ironic for my heart to handle.

**Comment by portal-chan** [comment]
You know, with the recent reputation of everyone thinking Agony is a joke, you're not doing them the best service by going around with an account that has "kill yourself" in it. Surely that won't make anyone take you more seriously.

Ignoring your pathetic attempt at sarcasm, yes, Isaac Character Editor is ironic. Not like that's ever been a huge secret.
