### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by KingisFire** [portal-chan/Isaac-Character-Editor#3]
I followed your video on [https://moddingofisaac.com/mod/16/isaac-character-editor](url)
![isaac](https://user-images.githubusercontent.com/32011327/30510839-953dd840-9acc-11e7-9824-413116a0b2ad.png)
But when I'm trying to run the .sh, even with sudo, I have this : 
`kingisfire@PC-Maxime:~/Documents/Jeux/Isaac_Character_Editor$ sh IsaacCharacterEditor.sh
IsaacCharacterEditor.sh: 12: IsaacCharacterEditor.sh: /home/kingisfire/Documents/Jeux/Isaac_Character_Editor/./IsaacCharacterEditor: Permission denied`

Why please ? And can u help me ?

**Comment by portal-chan** [comment]
@jerbear64

**Comment by jerbear64** [comment]
install gentoo

**Comment by KingisFire** [comment]
Hi, I installed getoo, I used it but I have always the same error. :(

**Comment by jerbear64** [comment]
Can you post an error log like you did on Ubuntu?

**Comment by KingisFire** [comment]
The only error I have is : 
```IsaacCharacterEditor.sh: 12: IsaacCharacterEditor.sh: /home/kingisfire/Documents/Jeux/Isaac_Character_Editor/./IsaacCharacterEditor: Permission denied```

**Comment by KingisFire** [comment]
@jerbear64 @portal-chan ?

**Comment by portal-chan** [comment]
🚶‍♀️
